services:
  - type: web
    name: DojoApp
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_MOCK_DATA
        value: "true"
      - key: PORT
        value: 3000
